sudo: false
language: node_js
before_script:
  - "npm install react@15.6.1"
  - "npm install react-dom@15.6.1"
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
before_install:
  - "npm install -g npm@5.5.1"
